name: build
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: ${{ matrix.target }} | ${{ matrix.os }} | ${{ matrix.channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: ['ios', 'android', 'web']
        channel: ['stable', 'beta']
        exclude:
          - os: ubuntu-latest
            target: ios
          - os: windows-latest
            target: ios
          # No web on stable yet
          - channel: stable
            target: web
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
              java-version: '8'
        - uses: subosito/flutter-action@v1
          with:
            channel: ${{ matrix.channel }}
        - name: enable web
          if: matrix.target == 'web'
          run: flutter config --enable-web
        # https://github.com/flutter/flutter/issues/59522#issuecomment-646208247
        - name: Fix iOS build bug
          if: matrix.target == 'ios'
          run: rm example/ios/Podfile
        - name: Test
          run: flutter test
        - name: Build ${{ matrix.target }}
          env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          run: |
            cd example
            TARGET=${{ matrix.target }}
            case $TARGET in
            ios)
            flutter build ios --release --no-codesign
            ;;
            android)
            flutter build appbundle
            ;;
            web)
            flutter build web
            ;;
            esac
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check scores
        # TODO: Once 1.0.0 lands, change min maintenance points to 100
        run: |
          MAINTENANCE_SCORE=${{ steps.analysis.outputs.maintenance }}
          HEALTH_SCORE=${{ steps.analysis.outputs.health }}
          if (( $(echo "$MAINTENANCE_SCORE < 90" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
          then
            echo "Scores must be min 90 for maintenance (until 1.0 ships), 100 for health."
            exit 1
          fi
  pod-lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/CocoaPods/CocoaPods/issues/5275#issuecomment-315461879
      - run: pod lib lint ios/sentry_flutter.podspec --skip-import-validation
  swift-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.1.0
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ktlint
        uses: ScaCap/action-ktlint@1.2
        with:
          github_token: ${{ secrets.github_token }}
